#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Deploy to test
          deployment: test
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - echo "Deploying to test environment"
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
         # after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            # - pipe: atlassian/checkstyle-report:0.2.0
            # - pipe: atlassian/email-notify:0.4.5
            #   variables:
            #     USERNAME: '<string>'
            #     PASSWORD: '<string>'
            #     FROM: '<string>'
            #     TO: '<string>'
            #     HOST: '<string>'
                # PORT: '<string>' # Optional.
                # TLS: '<boolean>' # Optional.
                # SUBJECT: '<string>' # Optional.
                # BODY_PLAIN: '<string>' # Optional.
                # BODY_HTML: '<string>' # Optional.
                # ATTACHMENTS: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.
      #- step:
      #    name: Security Scan
       #   script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
           # - pipe: atlassian/git-secrets-scan:0.4.3
      
            
            